/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.spark.plugins

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatCode
import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome.SUCCESS
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import java.io.File
import kotlin.test.Test

class SparkGradlePluginsFunctionalTest {
    @get:Rule
    val tempFolder = TemporaryFolder()

    private fun getProjectDir() = tempFolder.root
    private fun getBuildFile() = getProjectDir().resolve("build.gradle")
    private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")

    @Test
    fun `should apply java plugin and add test tasks for give modules`() {
        setupTestModuleWithExampleTest("testInt")
        setupTestModuleWithExampleTest("testFunctional")
        setupTestModuleWithExampleTest("testAcceptance")

        getBuildFile().writeText(
            """
                plugins {
                    id('net.spark.plugins')
                }
                
                repositories {
                    mavenCentral()
                }
                
                spark {
                    test {
                        module("testInt") {
                            useJunitPlatform()
                        }
//                        module(name = "testFunctional", useJunitPlatform = false)
//                        module(name = "testAcceptance", useJunitPlatform = false)
                    }
                }

                configurations {
                    testIntImplementation
                    testFunctionalImplementation
                    testAcceptanceImplementation
                }
                
                dependencies {
                   testIntImplementation "junit:junit:4.13.2"
                   testFunctionalImplementation "junit:junit:4.13.2"
                   testAcceptanceImplementation "junit:junit:4.13.2"
                }
            """.trimIndent()
        )

        // Run the build
        val runner = GradleRunner.create()
            .forwardOutput()
            .withPluginClasspath()
            .withArguments("testInt", "testFunctional", "testAcceptance")
            .withProjectDir(getProjectDir())

        assertThatCode { runner.build() }
        println("done")

//        assertThat(result.task(":testInt")?.outcome).isEqualTo(SUCCESS)
    }

    private fun setupTestModuleWithExampleTest(moduleName: String) {
        val testPackage = File(getProjectDir(), "src/$moduleName/java/net/spark")
        assertThat(testPackage.mkdirs()).isTrue

        File(testPackage, "ExampleTest.java").writeText(
            """
            package net.spark;

            import org.junit.Test;

            public class ExampleTest {
                @Test
                public void exampleTest() {
                    System.out.println("Example test");
                }
            }

        """.trimIndent()
        )

    }

}
