/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.spark.plugins

import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class SparkGradlePluginsTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("net.spark.plugins")

        // Verify the result
        assertNotNull(project.extensions.findByName("spark"))
    }
}
